### ISSUE TITLE
error with run debloat.ps1

### ISSUE THREAD

**Issue by nist3r** [kdpuvvadi/debloat-windows11#4]
Good evening, these are the steps I follow : 

1- Open PowerShell as administrator. 
2- run `Set-ExecutionPolicy Unrestricted` and I press Y
3- `cd c:\ `
4- `.\ debloat.ps1`

and I got this : 

```
En C:\debloat.ps1: 211 Carácter: 17
+             Sign&nbsp;up
+                 ~
No se permite usar el carácter de Y comercial (&). El operador & está reservado para un uso futuro; encierre un
símbolo de Y comercial entre comillas dobles ("&") para pasarlo como parte de una cadena.
En C:\debloat.ps1: 216 Carácter: 209
+ ... k Button--medium Button d-lg-none color-fg-inherit p-1">    <span cla ...
+                                                                 ~
El operador '<' está reservado para uso futuro.
En C:\debloat.ps1: 239 Carácter: 45
+             <ul class="list-style-none f5" >
+                                             ~
Falta la especificación de archivo después del operador de redirección.
En C:\debloat.ps1: 437 Carácter: 13
+       CI/CD &amp; Automation
+             ~
No se permite usar el carácter de Y comercial (&). El operador & está reservado para un uso futuro; encierre un
símbolo de Y comercial entre comillas dobles ("&") para pasarlo como parte de una cadena.
En C:\debloat.ps1: 496 Carácter: 45
+             <ul class="list-style-none f5" >
+                                             ~
Falta la especificación de archivo después del operador de redirección.
En C:\debloat.ps1: 511 Carácter: 45
+             <ul class="list-style-none f5" >
+                                             ~
Falta la especificación de archivo después del operador de redirección.
En C:\debloat.ps1: 1467 Carácter: 96
+ ... ="" data-disable-with="" data-dropdown-tracking="{&quot;type&quot;:&q ...
+                                                                 ~
No se permite usar el carácter de Y comercial (&). El operador & está reservado para un uso futuro; encierre un
símbolo de Y comercial entre comillas dobles ("&") para pasarlo como parte de una cadena.
En C:\debloat.ps1: 1467 Carácter: 103
+ ... a-disable-with="" data-dropdown-tracking="{&quot;type&quot;:&quot;blo ...
+                                                                 ~
No se permite usar el carácter de Y comercial (&). El operador & está reservado para un uso futuro; encierre un
símbolo de Y comercial entre comillas dobles ("&") para pasarlo como parte de una cadena.
En C:\debloat.ps1: 1467 Carácter: 146
+ ... &quot;type&quot;:&quot;blob_edit_dropdown.more_options_click&quot;,&q ...
+                                                                 ~
No se permite usar el carácter de Y comercial (&). El operador & está reservado para un uso futuro; encierre un
símbolo de Y comercial entre comillas dobles ("&") para pasarlo como parte de una cadena.
En C:\debloat.ps1: 1467 Carácter: 153
+ ... type&quot;:&quot;blob_edit_dropdown.more_options_click&quot;,&quot;co ...
+                                                                  ~
Falta una expresión después del operador unario ','.
No se notificaron todos los errores de análisis. Corrija los errores notificados e inténtelo de nuevo.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : AmpersandNotAllowed
```

Can you help me please? thanks!

**Comment by kdpuvvadi** [comment]
Where exactly is `debloat.ps1` placed? 

Can you try running the one liner? 

```shell
iwr https://git.io/debloat11 | iex
```

**Comment by nist3r** [comment]
> Where exactly is `debloat.ps1` placed?
> 
> Can you try running the one liner?
> 
> ```shell
> iwr https://git.io/debloat11 | iex
> ```

it is placed in `c:\debloat.ps1`

yes i can running`iwr https://git.io/debloat11 | iex` , but ! think debloat.ps1 have more options, is that  true?

**Comment by kdpuvvadi** [comment]
> think debloat.ps1 have more options, is that true?

NO, both are same. 


How did you save the `debloat.ps1` file? Those errors shouldn't be happening.

**Comment by nist3r** [comment]
I did right click on `debloat.ps1` and save link as.

maybe it is a problem with my pc... do u know the fix?

Im on Windows 11 formatted for less than a week and with all the Windows updates.

**Comment by kdpuvvadi** [comment]
You shouldn't save files from GitHub like that. You should first click on the file and then click on `raw`. That where you choose save as. 

Better solution would be cloning the repo and then run the file. If you have git installed, you can clone the repo with `git clone https://github.com/kdpuvvadi/debloat-windows11.git`. If not, you can install git with `winget install git.git`.

**Comment by nist3r** [comment]
> You shouldn't save files from GitHub like that. **_You should first click on the file and then click on `raw`_**. That where you choose save as.
> 
> Better solution would be cloning the repo and then run the file. If you have git installed, you can clone the repo with `git clone https://github.com/kdpuvvadi/debloat-windows11.git`. If not, you can install git with `winget install git.git`.

Thank you very much, you have been very kind and eager to help.

With this it works perfectly. 

> You should first click on the file and then click on raw. That where you choose save as.

**Comment by kdpuvvadi** [comment]
> With this it works perfectly.

you are welcome.
